## Map generation
imagej resources/maps/barn_282.pgm

## Parsing yaml files using hydra
# Job config
python3 train.py --cfg job
# Hydra config
python3 train.py --cfg hydra

## Training
python3 train.py quit_sim=true generate_data=true steps=10000 setup.model.envs=1
# NOTE!!! by default Webots rendering is disabled, it can be enabled by pressing the render button in the Webots GUI

## Testing
python3 test.py generate_data=true setup.model.steps=... setup.model.date=... setup.model.time=...
# NOTE!!! the setup.model.. must refer to an existing model, e.g. the one generated by the training command above