parameterized_reward:
  plot_wrapped_observation: false     # plot wrapped observation
  reward_buffer_size: 150             # buffer size for reward plotting
  r_at_goal: 250.0                    # reward for reaching the goal
  r_collision: -1500.0                # penalty for collision
  r_not_arrived: 0.0                  # reward for not arriving at the goal
  r_outside_map: -50.0                # penalty for going outside the map
  c_linear_d_progress: 50.0           # reward coefficient for linear progress
  c_path_d_dist: 0.0                  # reward coefficient for path distance
  c_path_d_heading: 0.0               # reward coefficient for path heading
  c_path_d_progress: 0.0              # reward coefficient for path progress
  c_path_d_progress_scaled_dist: 0.0  # reward coefficient for scaled path progress distance
  c_path_dist: 0.0                    # reward coefficient for path distance
  c_path_heading: 0.0                 # reward coefficient for path heading
  d_progress_high_pass_x: 0.01        # high pass filter threshold for progress
  d_progress_low_pass_x: 0.0          # low pass filter threshold for progress
  enable_d_progress_mapping: true     # enable mapping of d_progress to bias towards positive progress
  max_path_dist: 0.075                # max path distance [m], where r_path_dist ranges from pos to neg (max at 0 and ±0.4)
  max_path_heading: 0.18              # max path heading [rad], where r_path_heading ranges from pos to neg (max at 0 and ±0.4)
  plot_config:
    r_at_goal: { plot_style: { color: green, alpha: 0.55, linestyle: "--" }, plot_nr: 1 }
    r_outside_map: { plot_style: { color: orange, alpha: 0.55, linestyle: "--" }, plot_nr: 1 }
    r_collision: { plot_style: { color: red, alpha: 0.55, linestyle: "--" }, plot_nr: 1 }
    r_not_arrived: { plot_style: { color: red, alpha: 1, linestyle: "-" }, plot_nr: 0 }
    r_path_d_progress: { plot_style: { color: green, alpha: 1, linestyle: "-" }, plot_nr: 2 }
    r_linear_d_progress: { plot_style: { color: green, alpha: 1, linestyle: "-." }, plot_nr: 2 }
    r_path_dist: { plot_style: { color: blue, alpha: 1, linestyle: "-" }, plot_nr: 0 }
    r_path_d_dist: { plot_style: { color: blue, alpha: 1, linestyle: "-." }, plot_nr: 2 }
    r_path_d_progress_scaled_dist: { plot_style: { color: blue, alpha: 1, linestyle: "-" }, plot_nr: 2 }
    r_path_heading: { plot_style: { color: purple, alpha: 1, linestyle: "-" }, plot_nr: 0 }
    r_path_d_heading: { plot_style: { color: purple, alpha: 1, linestyle: "-." }, plot_nr: 2 }
    total_reward: { plot_style: { color: black, alpha: 1, linestyle: "-" }, plot_nr: 1 }