defaults:
  - sys_paths:
    - default_sys_paths
    
seed: 0           # random seed
max_steps: 1000   # maximum number of steps to run the environment
model:
  data: ???           # e.g. '2021-06-01'
  time: ???           # e.g. '15-42-18'
  use_best: false   # use the best model for evaluation
  steps: 10000000         # load model trained up to this number of steps
  deterministic: false    # use deterministic model
result_plotter:
  save: true
  show: true
  max_figure_axis: 25
  done_cause_colors:
    at_goal: 'lightgreen'
    outside_map: 'skyblue'
    collision: 'orange'
    max_nr_steps_reached: 'lightcoral'

# Configuration for Hydra
hydra:
  job:
    chdir: true