defaults:
  - _self_
  - paths:
    - general_sys_paths
  - data_generator:
    - cindy_test

# System paths for testing
paths:
  data_sets:
    root: ${paths.tmp}/data_sets/testing
  sim_resources:
    root: ${paths.tmp}/sim_resources/testing
  test_results: 
    root: ${hydra:runtime.output_dir}/test_results
    plots: ${paths.test_results.root}/plots
    logs: ${paths.test_results.root}/logs

seed: 0                 # random seed
generate_data: ???      # generate data
max_episode_steps: 600  # maximum episode steps
nr_episodes: 10         # number of episodes with random start and init from data loader
model:                  # model settings
  date: ???               # e.g. '2021-06-01'
  time: ???               # e.g. '15-42-18'
  steps: ???            # load model trained up to this number of steps (-1 is use_best_model)
  deterministic: false    # use deterministic model
plotter:                # result plotter settings
  save: true              # save the plot
  show: true              # show the plot
  max_axis: 25            # maximum axis for the plot
  done_cause_colors:      # colors for done causes
    at_goal: 'lightgreen'
    outside_map: 'skyblue'
    collision: 'orange'
    max_nr_steps_reached: 'lightcoral'

# Configuration for Hydra
hydra:
  run:
    dir: outputs/testing/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true