name: webots
sample_time: 0.05       # sample time [s]
mode: fast              # simulation mode (fast or real-time)
no_rendering: true      # rendering mode (true or false)
world_file_name: webots_world_file.wbt

## TODO: Add back proto_reconfiguration
# proto_reconfiguration:    # reconfiguration of the Webots proto files
#   template_name: RpLidarA2_template.proto  # name of the proto template file (input)
#   output_name: RpLidarA2.proto  # name of the output proto file (output)
#   substitutions:          # substitutions for the proto template
#     defaultFrequency: 20          # default frequency of the lidar [Hz]
#     fieldOfView: 6.283185307      # field of view of the lidar [rad]
#     horizontalResolution: 64      # horizontal resolution of the lidar [steps]
#     maxFrequency: 40              # maximum frequency of the lidar [Hz]
#     maxRange: 5.0                 # maximum range of the lidar [m]
#     minFrequency: 20              # minimum frequency of the lidar [Hz]
#     minRange: 0.05                # minimum range of the lidar [m]
#     near: 0.05                    # near clipping distance of the lidar [m]
#     noise: 0.0                    # noise level of the lidar measurements
#     numberOfLayers: 1             # number of layers of the lidar
#     resolution: 0.05              # resolution of the lidar [m]
#     type: fixed                   # type of the lidar (fixed or rotating)